# Generated by Django 5.2.4 on 2025-07-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='件名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('start_date', models.DateField(verbose_name='期限_開始日')),
                ('until_date', models.DateField(verbose_name='期限_終了日')),
                ('done_at', models.DateField(blank=True, null=True, verbose_name='完了日')),
            ],
        ),
    ]
